version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: expense_tracker_database
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
